### ISSUE TITLE
🛠️ [TASK] : Add filter to OpenAPI document prior to frontend code generation.

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#1172]
### Summary

Filter the OpenAPI document so that front end code generation is restricted.

### Description

The front end does not need to implement every endpoint.
Implement a filter that takes the raw OpenAPI specification from the backend and removes all endpoints that should not be used by the front end.

This will reduce the size and scope of the generated code and help prevent issues while endpoints are developed in the backend.

This tool will be used for this process: https://www.npmjs.com/package/openapi-format

This configuration will filter anything thats unused all draft endpoints, or endpoints used by the legacy stack/k8s.

```yaml
tags:
  - Health
  - Legacy
operations:
  - '*::/api/draft/*'
unusedComponents:
  - schemas
  - parameters
  - examples
  - headers
  - requestBodies
  - responses
``` 

This needs to be implemented as a `build target` which takes the published raw OpenAPI document artifact from the `cat-gateway` build and produces a "Filtered" OpenAPI output artifact, which would then be used by the code generation build target for flutter.
